services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "11"
      RAM_SIZE: "8G"
      CPU_CORES: "8"
      # KEYBOARD
      # ARGUMENTS: "-device usb-host,vendorid=0x03f0,productid=0x0591"
      # MOUSE
      # ARGUMENTS: "-device usb-host,vendorid=0x1038,productid=0x184c"
    devices:
      - /dev/kvm
      - /dev/net/tun
      # - /dev/bus/usb
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 3389:3389/tcp
      - 3389:3389/udp
    volumes:
      - ./windows:/storage
    restart: always
    stop_grace_period: 2m
